//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QueueEntities : DbContext
    {
        public QueueEntities()
            : base("name=QueueEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Type> Type { get; set; }
    
        public virtual ObjectResult<q_Load_List_Result> q_Load_List()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<q_Load_List_Result>("q_Load_List");
        }
    }
}
